name: Deploy typo3lexikon.de with Hugo

on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "build"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.142.0
    steps:
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb
      - name: Install Dart Sass
        run: sudo snap install dart-sass
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Build with Hugo
        env:
          # For maximum backward compatibility with Hugo modules
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
          TZ: Europe/Berlin
        run: |
          hugo \
            --gc \
            --minify
      - uses: actions/upload-artifact@v4
        with:
          name: hugo-site-artifact
          path: public

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: hugo-site-artifact
          path: public
      - name: "Deploy via SFTP Mirror (lftp)"
        env:
          SSH_KEY: ${{ secrets.SSH_PRIV_KEY }}
          HOST: ${{ secrets.SSH_HOST }}
          USER: ${{ secrets.SSH_USER }}
        run: |
          # Install lftp as it is not pre-installed on the runner
          sudo apt-get update && sudo apt-get install -y lftp
          
          # Setup SSH directory and store the private key
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          
          # Use lftp to synchronize the local public folder with the remote server.
          # --reverse: Upload local files to remote
          # --delete: Remove remote files that no longer exist locally
          # --parallel=10: Speed up transfer by using multiple connections
          lftp -u "$USER", sftp://$HOST \
            -e "set sftp:connect-program 'ssh -a -x -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no'; \
                mirror --reverse --delete --parallel=10 --verbose public/ ${{ secrets.SSH_PATH }}; \
                quit"
